#No language required so just use ruby to avoid warnings in travis yml linter
language: ruby
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils

script: xmllint --noout --schema http://www.w3.org/2001/XMLSchema.xsd ./event-logging.xsd
